services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "dearmoby@docker.com"
      PGADMIN_DEFAULT_PASSWORD: "mysecretpassword"
    volumes:
       - pgadmin:/root/.pgadmin

volumes:
  postgresdata:
  pgadmin:

